config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root "home#home"
  get 'users', to: "home#home"

  resources :categories, only: [:index, :new, :create]  do
    resources :exchanges, only: [:index, :new, :create]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :slots
  has_many :exchanges, through: :slots

  validates_presence_of :user
  validates :name, presence: true, length: { maximum: 30 }
  validates :icon, presence: true, length: { maximum: 255 }

  def total_amount
    total = 0
    exchanges.each do |exchange|
      total += exchange.amount
    end
    total
  end
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :slots
  has_many :categories, through: :slots

  validates_presence_of :author
  validates_presence_of :name, :amount
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :category
  belongs_to :exchange
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 30 }
  has_many :categories
  has_many :exchanges, foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @categories = Category.where(user: current_user)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_exchange, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @category = Category.find(params[:category_id])
    @exchanges = @category.exchanges.order(created_at: :desc)

    redirect_to new_user_session_path, notice: 'Can not access this ressource' if @category.user != current_user
  end

  def new
    @category = Category.find(params[:category_id])
    @exchange = Exchange.new
  end

  def create
    @exchange = Exchange.new(exchange_params)
    @exchange.author = current_user
    @category = Category.find(params[:category_id])
    @category.exchanges << @exchange

    respond_to do |format|
      if @exchange.save
        format.html { redirect_to category_exchanges_path(@category), notice: 'Exchange was successfully created.' }
        format.json { render :show, status: :created, location: @exchange }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exchange
    @exchange = Exchange.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def exchange_params
    params.require(:exchange).permit(:name, :amount)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    redirect_to categories_path if user_signed_in?
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(_resource)
    categories_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_category.html.erb
<div class="bg-white flex justify-between p-5 m-6 py-8 text-black " id="<%= dom_id category %>">
  <div class="basis-16"><img src="<%= category.icon%>" class="w-24"></div>
  <div><%= category.name%></div>
  <div><%= category.total_amount%>$</div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: 'flex  flex-col') do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-8">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="field mb-8">
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div class="actions blue p-6 text-white flex justify-center">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<section class="flex flex-col h-screen">
  <div class="blue flex justify-between py-4 text-white">
    <img src="icons/bars-solid.svg" alt="menu">
    <div>CATEGORIES</div>
    <%= button_to "X", destroy_user_session_path, method: :delete  %>
  </div>
  <p style="color: green" class="py-2"><%= notice %></p>
  <div id="categories" class="grow">
    <% @categories.each do |category| %>
      <%= link_to category_exchanges_path category do %>
        <%= render category %>
      <%end%>
    <% end %>
  </div>
  <div class="bg-lime-500 flex justify-center py-2 text-white"><%= link_to "Add a new category", new_category_path %></div>
</section>

app/views/categories/new.html.erb
  <div class="blue flex justify-between p-6 text-white">
    <div class="justify-self-start"><%= link_to "<", categories_path %></div>
    <div>Create new category</div>
<%= button_to "X", destroy_user_session_path, method: :delete  %>
</div>
  
  </div>

<section class="mx-auto h-screen flex flex-col justify-center items-center">
  <div class="bg-white p-8">
    <div class="grow flex  flex-col justify-center items-center">
      <%= render "form", category: @category %>

    </div>

  </div>
</section>

app/views/exchanges/_exchange.html.erb
<div class="bg-white flex p-5 m-6 py-8 text-black ">
  <div class="basis-16"><%= exchange.amount%></div>
  <div><%= exchange.name%></div>
</div>

app/views/exchanges/_form.html.erb
<%= form_with(model: exchange, url: category_exchanges_path(@category)) do |form| %>
  <% if exchange.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>
      <ul>
        <% exchange.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mb-8">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div class="field mb-8">
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>
  <div class="actions blue p-6 text-white flex justify-center">
    <%= form.submit %>
  </div>
<% end %>

app/views/exchanges/edit.html.erb
<h1>Editing exchange</h1>

<%= render "form", exchange: @exchange %>

<br>

<div>
  <%= link_to "Show this exchange", @exchange %> |
  <%= link_to "Back to exchanges", exchanges_path %>
</div>

app/views/exchanges/index.html.erb
<section class="flex flex-col h-screen">
  <div class="blue flex justify-between p-6 text-white">
    <div class="justify-self-start"><%= link_to "<", categories_path %></div>
    <div>All transaction for <%= @category.name %> </div>
    <%= button_to "X", destroy_user_session_path, method: :delete  %>
  </div>
  <div class="bg-white flex justify-center py-2 text-black ">TOTAL : <%=@category.total_amount%>$ </div>
  <div id="exchanges" class="grow">
    <p style="color: green" class="py-2"><%= notice %></p>
    <% @exchanges.each do |exchange| %>
      <%= render exchange %>
    <% end %>
  </div>
  <div class="bg-lime-500 flex justify-center py-2 text-white"><%= link_to "New exchange", new_category_exchange_path(@category) %></div>
</section>

app/views/exchanges/new.html.erb
<div class="blue flex justify-between p-6 text-white">
  <div class="justify-self-start"><%= link_to "<", category_exchanges_path(@category) %></div>
  <div>Create new exchange</div>
  <%= button_to "X", destroy_user_session_path, method: :delete  %>
</div>
</div>
<section class="mx-auto h-screen flex flex-col justify-center items-center">
  <div class="bg-white p-8">
    <div class="grow flex  flex-col justify-center items-center">
      <%= render "form",exchange: @exchange %>
    </div>
  </div>
</section>

app/views/exchanges/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @exchange %>

<div>
  <%= link_to "Edit this exchange", edit_exchange_path(@exchange) %> |
  <%= link_to "Back to exchanges", exchanges_path %>

  <%= button_to "Destroy this exchange", @exchange, method: :delete %>
</div>

app/views/home/home.html.erb
<section class="p-5 flex flex-col h-screen">
  <div class="grow flex justify-center items-center">
    <h1 class="dark-grey text-4xl">Forteresse
    </h1>
  </div>
  <div class="blue flex justify-center py-8 text-white hover:bg-blue-900"><%= link_to 'LOG IN', new_user_session_path %></div>
  <div class="flex justify-center py-8 grey hover:bg-slate-400 hover:text-white"><%= link_to 'SIGN UP', new_user_registration_path %></div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <main class="container mx-auto flex flex-col h-screen ">
      <%= yield %>
    </main>
  </body>
</html>